_all:
    @just --list

# Format
fmt:
    poetry run ruff format .

# Lint
lint:
    poetry run ruff check .
    poetry run mypy .

# Test
test:
    poetry run pytest

# Run
run *ARGS:
    poetry run python httpcat/main.py {{ ARGS }}