_all:
    @just --list

# Format
fmt:
    deno fmt

# Lint
lint:
    deno lint

# Run
run *ARGS:
    deno run --allow-read --allow-net src/main.ts {{ARGS}}

# Test
test:
    deno test

# Build
build:
    deno compile --allow-read --allow-net --output=httpcat-deno src/main.ts