name: httpcat_dart
description: Something.
version: 1.0.0

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  enough_ascii_art: ^1.1.0
  http: ^1.2.1
  http_status_code: ^0.0.2
  image: ^4.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
